name: Terraform GCP

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write GCP credentials
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > gcp-key.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}